add_requires("cli11 2.6.1", {system = false})
add_requires("nlohmann_json 3.12.0", {system = false})
add_requires("fmt 12.1.0", {system = false, configs = {header_only = true}})
add_requires("spdlog 1.17.0", {system = false, configs = {fmt_external = true}})
add_requireconfs("spdlog.fmt", {override = true, version = "12.1.0", system = false, configs = {header_only = true}})
add_requires("libcurl 8.11.0", {alias = "libcurl", system = false, configs = {mbedtls = true}})
add_requires("sqlite3 3.52.0", {system = false, configs = {cflags = "-DSQLITE_ENABLE_FTS5"}})
add_requires("cpp-httplib 0.37.2", {system = false})
add_requires("stdexec 2024.12.08", {system = false})
add_requires("rapidhash 1.0", {system = false})
add_requires("replxx 2021.11.25", {system = false})
add_requires("mbedtls 3.6.1", {system = false})
add_requires("catch2 3.7.1", {system = false})
add_requires("simdutf 8.0.0", {system = false})
add_requires("uni_algo 1.2.0", {system = false})
add_requires("ctre 3.10.0", {system = false})
add_requires("magic_enum 0.9.7", {system = false})
